### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by KossyfasStavros** [DavidEpisode/Physics-Simulation#1]
I'm not sure that I would call it an issue yet or if I am missing anything fundamental, but I can't run the created solution. I have tried downloading the libraries, including them and other directories that I thouht I would need, but there is no way that the code will run. Before anything else, could you please give instructions about how you make it work? What versions of Visual Sudio, Cmake and libraries are you using? Also, what configuration is it supposed to run on - win32, win64, universal? Thanks in advance!

**Comment by davidzhangxm** [comment]
Hi, I run this toy project on my macbook pro with OS Mojave. And I was using clion which directly opens a cmake project then. All necessary deps are specified at CMakeLists.txt. You should install those libs youself and tell you cmake to find them. Also if you are experiencing issue on running, I'd like to suggest that you run opengl application successfully first which means a window can be launched. The final result is as this [video](https://www.youtube.com/watch?v=pahNLit77dQ&feature=youtu.be) shows.

**Comment by KossyfasStavros** [comment]
Oh, ok! There are a lot of differences! I have installed the latest versions of the libraries specified in CMakeLists.txt and my problems are not with opengl, I have already run a few applications successfully. Thanks for the answer, anyway. I will keep looking into it!
